import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'dart:io' show Platform;

/// Firebase configuration — generated by `flutterfire configure`.
///
/// These are CLIENT-SIDE identifiers, not secrets. The same values exist in
/// the committed android/app/google-services.json. Security is enforced by
/// Firebase Security Rules on the server, not by hiding these values.
///
/// No dependency on AppEnv or dotenv — keeps Firebase init simple and
/// avoids any circular import or load-order issues.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (Platform.isAndroid) return android;
    throw UnsupportedError(
      'DefaultFirebaseOptions have not been configured for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9c-ngIOMfNVq91c2PHOLotcz7bud0fCg',
    appId: '1:612192598689:android:940f5cc4630eb337d90ee0',
    messagingSenderId: '612192598689',
    projectId: 'sheshield-bd387',
    storageBucket: 'sheshield-bd387.firebasestorage.app',
  );
}
